version: '3.8'

services:
  openai-gemini:
    build: .
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
